### ISSUE TITLE
Gradle Cobertura performCoverageCheck is always skipped

### ISSUE THREAD

**Issue by prithulagta** [stevesaliman/gradle-cobertura-plugin#79]
Hi,

I am running into a issue where I have a groovy project and using cobertura plugin version (net.saliman:gradle-cobertura-plugin:2.2.4). The gradle version I am using is 2.2.1. I am running gradle clean build test, followed by gradle cobertura. When I run gradle cobertura, below is the outcome:
Stub:compileJava UP-TO-DATE
:Stub:compileGroovy UP-TO-DATE
:Stub:processResources UP-TO-DATE
:Stub:classes UP-TO-DATE
:Stub:instrument
Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
:Stub:copyCoberturaDatafile
:Stub:generateModuleManifest
:Stub:compileTestJava UP-TO-DATE
:Stub:compileTestGroovy UP-TO-DATE
:Stub:processTestResources UP-TO-DATE
:Stub:testClasses UP-TO-DATE
:Stub:test
:Stub:generateCoberturaReport
Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Report time: 120ms
Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Report time: 308ms
:Stub:performCoverageCheck SKIPPED
:Stub:coberturaReport UP-TO-DATE
:Stub:cobertura

The coverage.xml is generated, but the file has hits="0" and condition-coverage="0% for every line number element. As a result SonarQube shows Coverage as 0.

My build.gradle has:

project(':Stub') {

	apply plugin: 'cobertura'
	test {

		cobertura {
   			 coverageFormats = ['html', 'xml']				
   			 coverageIgnoreTrivial = true					
   			 coverageIgnores = ['org.slf4j.Logger.*']			
   			 coverageReportDir = file("$buildDir/reports/cobertura")	
			 coverageSourceDirs << project.sourceSets.main.groovy.srcDirs
			  
		}
	}

}

Any clue?

**Comment by unionx** [comment]
Same issue here.

**Comment by ghost** [comment]
-

**Comment by pinguinkiste** [comment]
I have the same problem with 2.2.8. It seems like the plugin tests are not run during a build. There is a failing test which checks that the source directory is set/found. So it *may* be the case that the plugin has no source directory and skips the test. (But I have no facts for now, this is just a gut feeling.)

**Comment by stevesaliman** [comment]
When you say the plugin tests are failing, do you mean the cobertura plugin has a failing unit test?

I just tried a build with gradle 2.5, and all the tests are working.  Are you on a windows box by chance?  I'm wondering if there is different behaviour with paths between windows and Linux platforms.

**Comment by pinguinkiste** [comment]
I meant the tests of the Gradle Cobertura plugin. It seems like on a regular build they are not run at all (at least on my box). I had to remove the project.tasks.test.configure block in build.gradle to make them run. There are two failures in the unit tests. The "integration test" in testclient do not work at all. After fixing some signing settings, they start but never finish. ( I introduced timeouts up to 30 minutes, but they always hit that.)

I'm on a Linux box (Debian Jessie).

**Comment by pinguinkiste** [comment]
How do you usually build? Running `gradle clean install` does not run the tests on my box. `gradle clean build` or `gradle clean test`do with one failing test. I disabled the "integration tests" by adding

```groovy
test {
	exclude '**/*ExecutionTest.class'
}
```
to `build.gradle`. I tried it with Gradle wrapper and local installations of versions 2.4, 2.5 and 2.6. All show the same behavior.

**Comment by pinguinkiste** [comment]
Some more information on that. I did several tests in several environments. A checkout of `master` "works" - except that it does not run the tests. `gradle --info clean test` shows that no tests are run. This is also shown in the generated reports. When removing the line reading `useTestNG()` from `build.gradle` runs the test with already mentioned failures. This is reproducible with different versions of JDK and Gradle.

Additionally, in IntelliJ IDEA running the tests always fails. With a clean checkout of `master` it fails with
```groovy
test
:test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [*]
```
Commenting out the TestNG line leads to the same behavior as the command line: One failing unit test and all tests in CPExecutionTest hanging. Still not sure what the proper way to fix it.

**Comment by stevesaliman** [comment]
Well, the testNG thing makes sense - I write all my unit tests in Junit.  I'm just surprised that the testNG thing has been hiding in the build file all along, and I've never noticed it before...

I think we can remove the entire ```project.tasks.test.configure``` section, since Junit seems to be able to find all the tests without it.

I'm now seeing the same behavior as you are, though I seem to remember it running OK from Intellij.  I'll look into it when I get a chance, though it will probably be next week before I can get to it.

Thank you for finding this.

**Comment by pinguinkiste** [comment]
No hurry, I'm glad you can reproduce it. I will have some time in the next days and I hope I'll get around to look a bit deeper into it. (If you don't mind.)

**Comment by stevesaliman** [comment]
I've fixed the unit tests, and the now run and pass.  Thanks again for bring this up.

The test that was failing was due to code that was moved to fix Issue #53, but the test was never cleaned up.  The code used to set the source directories at apply time, but this was causing inconsistent behaviour based on the order in which plugins were applied, which was obviously undesirable.  The fix for Issue #53 was to move that code to execution time.  The plugin now uses ```coverageSourceDirs``` only if it has a value, otherwise it will generate a default at execution time that will include java, groovy, and scala sources depending on what plugins are applied. This fix was made in version 2.2.5.

From the build file snippet you gave, it looks like you are using the standard location for your Groovy source code, which the plugin should be able to find with the default configuration.  What happens if you remove the ```coverageSourceDirs``` from your build file?

**Comment by Christian2000** [comment]
Hi. I have the same problem as above. I was just wondering if whats fixed above is the unit-test or the actuall error? Thank you!

**Comment by stevesaliman** [comment]
The unit test error has been fixed.  I haven't heard anything back yet about whether or not the original groovy project remains.  Are you having the same problem with the latest version of the plugin?

**Comment by Christian2000** [comment]
Thank you for your swift reply!

I have tried the latest version (and built snapshot from latest sources) and still get have the 0 coverage issue above with
:performCoverageCheck SKIPPED

**Comment by stevesaliman** [comment]
For those that are experiencing skipped coverage checks:

The ```cobertura``` task is designed to produce coverage reports, but it doesn't check coverage.  The idea is that there is no point running tests with coverage without seeing the coverage report, but a lot of people will want to get coverage reports without failing the build for coverage levels.

If you add the ```coberturaCheck``` task to your builds, the plugin should perform a coverage check.

**Comment by maxiaohao** [comment]
Hi stevesaliman,

According to your gradle cobertura plugin [usage doc](https://github.com/stevesaliman/gradle-cobertura-plugin/blob/master/usage.md#tasks), the following gradle commands should do a coverage check and generate reports:

`gradle clean`
`gradle coberturaCheck`
`gradle test`

But in my case it does not, and all the cobertura related tasks are still '**SKIPPED**' during the gradle build. However, a `gradle cobertura` command can generate reports. 

My environment:
Ubuntu 14.04LTS 64bit
Oracle JDK 1.8.0_60-64bit
Gradle 2.14.1

Attached is my example code that doesn't work.
[skip-example.tar.gz](https://github.com/stevesaliman/gradle-cobertura-plugin/files/530867/skip-example.tar.gz)

How can I get the coverage check work correctly? If you could give some help, I will appreciate a lot!

Thanks!

**Comment by maxiaohao** [comment]
Hi, I at last found that 
`gradle clean`
`gradle coberturaCheck`
`gradle test`
won't work but a single `gradle clean coberturaCheck test` would do:)

Thanks.

**Comment by stevesaliman** [comment]
I added some clarification to the usage doc to mention that ```coberturaCheck``` doesn't run tests by itself.

Also, I've run into issues in the past when clean was part of a larger list of tasks.  It almost seemed as if Gradle was caching some of the artifacts.  you should be able to run ```gradle clean``` followed by ```gradle test coberturaCheck```

**Comment by maxiaohao** [comment]
Got clarified. Thank you!

**Comment by rajademo** [comment]
Need some help
cobertura {
    coverageFormats = ['xml']	
    coverageIgnoreTrivial = true 			
    coverageDirs = 	["$testClassesDir"]
    coverageIncludes = ['.*\\*.class.*']
    coverageExcludes =  ['.*\\*Test.class.*']
    coverageSourceDirs = ["$appRootSource"] 
}

Still the cobertura-report is getting updated

**Comment by stevesaliman** [comment]
I'm sorry, but I have no idea what you are asking from your description, but my hunch is that it isn't related to this closed issue.  

If you are still having an problem you can open a new issue with more details and I can try to take a look at it.

**Comment by stevesaliman** [comment]
I'm sorry, but I have no idea what you are asking from your description, but my hunch is that it isn't related to this closed issue.  

If you are still having an problem you can open a new issue with more details and I can try to take a look at it.
